<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'name' => 'Baby Macaroon - Macaron Toples isi 50pcs - Cookies',
                'price' => 94900.0,
                'weight' => 500,
                'stock' => 500,
            'description' => '<p>Macaron adalah kue khas asal Perancis.<br>Decookieshouse Macaroon dibuat dari tepung almond asli, dengan isian (filling) coklat ganache ya Harga murah tapi RASA MAHAL &amp; 100% HALAL</p><ul><li>Baby Macaron kemasan toples isi 50pcs</li><li>Size diameter kurleb 2-2,5cm</li><li>Barang dikirim sehari setelah order</li><li>Pengiriman setiap hari jam 6 sore</li><li>Dikirim mix raaa</li></ul><p>Warna dan Rasa Macaron</p><ol><li>Merah | Strawberry<br>&nbsp;</li><li>Merah Bata | Red Velvet</li><li>Putih | Vanila</li><li>Hijau Muda | Greentea</li><li>Hijau Tua | Mint</li><li>Pink | Raspberry</li><li>Biru Muda | Salt Caramel</li><li>Biru Tua | Bubble Gum</li><li>Peach Kopi | Tiramisu10 .Abu-Abu | Cappuccino11 .Coklat Milo | Milo12 .Coklat Oreo | Oreo13 .Coklat Tua | Coklat14 .Orange | Orange15 .Kuning | Lemon16 .Ungu Muda | Blueberry17 .Ungu Tua | Taro</li></ol>',
                'img_main' => 'products/1/ujIEXOwUHR90TpXZ5VZ7GMewy3dhZs3SEx9uz1DG.webp',
                'img_top' => NULL,
                'img_side' => NULL,
                'img_front' => 'products/1/ovJHaGm9gjX5n8Gon6ePBv3gOCe6zzGrvM8Zk9Q1.png',
                'img_other' => NULL,
                'video' => NULL,
                'main_category' => 'Kue',
                'sub_category' => 'Kue Kering',
                'reg_code' => NULL,
                'expired' => '2022-01-01',
                'durability' => 30,
                'preorder' => 1,
                'discount' => 1,
                'discount_price' => 89900.0,
                'hide' => 0,
                'created_at' => '2022-01-25 10:43:52',
                'updated_at' => '2022-01-25 11:29:25',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'name' => 'KUE KERING SATU KACANG IJO',
                'price' => 11900.0,
                'weight' => 163,
                'stock' => 191,
            'description' => '<p><strong>MOHON DIBACA TERLEBIH DAHULU</strong></p><ul><li>Kue Satu Rasa Kacang Hijau.</li><li>Berat sekitar 200gr = Isi 20pcs.</li><li>Expired/kadaluarsa panjang. Chat untuk informasi lebih lanjut.</li><li>SELALU READY STOCK.</li><li>Semua foto yang tercantum adalah REAL PICTURE (Langsung difoto oleh seller).</li><li>Ditimbang dengan timbangan digital. Jadi berat PASTI sesuai.</li><li>Pengiriman dari Depok, Jawa Barat.</li><li>Dipacking dengan kardus tebal dan bubblewrap FREE TANPA BIAYA TAMBAHAN dari toko kami. Semua produk yang dikirim sudah dimaksimalkan supaya dapat meminimalisir hancur selama perjalanan. Kerusakan selama perjalanan BUKAN tanggung jawab seller.</li><li>PERHATIAN: Untuk keripik atau produk yang mudah hancur lainnya walaupun sudah dipacking dengan bubblewrap dan kardus masih bisa kemungkinan hancur karena proses pengiriman, produk yang mudah hancur tidak bisa sampai ke tangan pembeli dalam keadaan utuh 100%. Jadi mohon pengertiannya kalau hancur sedikit WAJAR. Jika ingin produk DIJAMIN utuh semua ketika sampai tujuan harap menggunakan pengiriman SAMEDAY/INSTANT.</li><li>HARAP MEMBACA SYARAT &amp; KETENTUAN DI CATATAN TOKO SERTA DESKRIPSI PRODUK SEBELUM BERTANYA ATAU MENGAJUKAN KOMPLAIN. Jika membeli kami menganggap pembeli sudah paham dan menyetujui syarat &amp; ketentuan kami.</li><li>Mohon jika ada KOMPLAIN mengenai kondisi barang dapat menghubungi admin terlebih dahulu via chat sebelum memberikan ulasan. Jika kerusakan/kekurangan memang karena kelalaian kami PASTI kami TANGGUNG JAWAB. Mohon maaf sekali jika komplain di ulasan TIDAK AKAN KAMI GANTI. Please be a smart buyer.</li></ul>',
                'img_main' => 'products/1/MCJTYEChESEKX6fbNOZa3jAUswOoQhfc22kriNvN.webp',
                'img_top' => NULL,
                'img_side' => NULL,
                'img_front' => 'products/1/XLOdhTef69pgnLHrTEfADCe1Npp3xgvO0E73mPQP.webp',
                'img_other' => NULL,
                'video' => NULL,
                'main_category' => 'Kue',
                'sub_category' => 'Kue Kering',
                'reg_code' => NULL,
                'expired' => '2025-01-07',
                'durability' => NULL,
                'preorder' => 1,
                'discount' => 1,
                'discount_price' => 7800.0,
                'hide' => 0,
                'created_at' => '2022-01-25 10:49:36',
                'updated_at' => '2022-01-25 10:49:36',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'name' => 'Kue Ubi Ungu Wijen DEL',
                'price' => 23500.0,
                'weight' => 400,
                'stock' => 10,
                'description' => '<p>Kue ubi ungu wijen Del dibuat dari ubi jalar yang berwarna ungu. sehingga kue ini tidak menggunakan pewarna tambahan.</p><p>P.IRT 215 1371 02 1406 20<br>Berat bersih : 300gr<br>Expired : 3 bulan sejak tanggal dikirim<br>Saran Konsumsi : 6-7 minggu sejak produk di terima</p><p>Komposisi : Ubi Ungu - Tepung Terigu - Gula - Mentega - Wijen</p>',
                'img_main' => 'products/1/lRjMH6LAIy7qzPd69j3VSPB0v7TZ0DfYwLnJONko.webp',
                'img_top' => 'products/1/nKF8ZmHFHpLL7JWH49yTqlQtCclROC1p7pi1tSBD.webp',
                'img_side' => NULL,
                'img_front' => 'products/1/E0BKFMebOItu8GhDd9MqiE12gTmpwmpy3ZawtRic.webp',
                'img_other' => NULL,
                'video' => NULL,
                'main_category' => 'Cemilan / Snack',
                'sub_category' => 'Keripik',
                'reg_code' => '215 1371 02 1406 20',
                'expired' => '2022-01-01',
                'durability' => 60,
                'preorder' => 1,
                'discount' => 1,
                'discount_price' => 22500.0,
                'hide' => 0,
                'created_at' => '2022-01-25 10:56:58',
                'updated_at' => '2022-01-25 10:56:58',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'name' => 'kue beras korea tteokbokki topoki kofu',
                'price' => 17472.0,
                'weight' => 300,
                'stock' => 250,
                'description' => '<h3>&nbsp;</h3><p>kue beras korea tteokbokki topoki kofu 200 gr lengkap dengan saus bumbunya isi 18 batang halal dan lezat<br><br><br><br>Produk tahan 2 minggu disuhu ruang dan 3 bulan di dalam kulkas<br><br><br><br>jadi aman untuk pengiriman ke seluruh indonesia<br><br><br><br>dan bisa menggunakan jasa kirim apapun<br><br><br><br>tunggu apalagi silahkan diorder sebelum kehabisan<br><br><br><br>suka kpop?, Kdrama?pasti suka kofu topokki</p>',
                'img_main' => 'products/1/6G4iwUbB5QeL0YPEfsua4mQpHRrJIgfIkb7jV2eS.webp',
                'img_top' => NULL,
                'img_side' => NULL,
                'img_front' => 'products/1/6tkS3k0fDLcQ74H1pX10MXw8YOTT8ylU3gmg0par.webp',
                'img_other' => NULL,
                'video' => NULL,
                'main_category' => 'Cemilan / Snack',
                'sub_category' => 'Camilan Instant',
                'reg_code' => NULL,
                'expired' => '2022-01-01',
                'durability' => 14,
                'preorder' => 0,
                'discount' => 0,
                'discount_price' => NULL,
                'hide' => 0,
                'created_at' => '2022-01-25 11:00:49',
                'updated_at' => '2022-01-25 11:00:49',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'name' => 'Kue Soes Coklat Lumer Mini Sus Cokelat Melted Choco Cake',
                'price' => 33900.0,
                'weight' => 610,
                'stock' => 500,
            'description' => '<p>--Soes Coklat--<br><br>Kemasan : 500 Gram<br><br><br><br>Siapa yg ingin nyemil coklat mini yg manis? Yuk dicoba, kue soes coklat ini. Kue soes berukuran imut ini mempunyai tekstur kering di bagian luar dan begitu CREAMY di bagian dalamnya. Dan juga soes ini memberikan sensasi coklat yg manis, serta memberikan sensasi LUMER di setiap gigitannya. Ohh iya, Soes Coklat ini menggunakan bahan alami loh tanpa pewarna buatan sehingga aman untuk dikonsumsi seluruh keluarga tercinta.<br><br><br><br>Sekali gigit....yo langsung nyeesss...MELELEH Coklatnya di dalam mulut.<br><br>Yuk diorder^^<br><br><br><br>Reseller and Dropshipper are Welcome<br><br>Please DM : )</p>',
            'img_main' => 'products/1/lj7fzUfbWcjrqxqUCL31QpHW36MtHn4VOKKr5k4E.webp',
            'img_top' => NULL,
            'img_side' => NULL,
            'img_front' => 'products/1/rvqm6hBFYNpQ4PcZP54wuqi9yt0LUBQptYyQ6kCa.webp',
            'img_other' => NULL,
            'video' => NULL,
            'main_category' => 'Cemilan / Snack',
            'sub_category' => 'Cokelat',
            'reg_code' => NULL,
            'expired' => '2022-12-19',
            'durability' => 30,
            'preorder' => 0,
            'discount' => 1,
            'discount_price' => 29000.0,
            'hide' => 0,
            'created_at' => '2022-01-25 11:05:13',
            'updated_at' => '2022-01-25 11:05:13',
        ),
        5 => 
        array (
            'id' => 6,
            'user_id' => 1,
            'name' => 'bakpia kacang ijo hijau tolitolino kue pia enak lezat toples',
            'price' => 35000.0,
            'weight' => 490,
            'stock' => 100,
        'description' => '<p>* Fresh from the oven produksi setiap hari<br><br>* 100% halal<br><br>* Kue pia cemilan yang enak dan lezat<br><br>* Cocok untuk teman minum teh ataupun kopi<br><br>* Dibungkus dengan toples yang bisa dibuka tutup sehingga setelah dibuka kemasannya, kue yang tersisa tetap fresh<br><br>* Dibungkus dengan bungkusan plastik untuk masing2 kue sehingga mudah dibawa kemana mana dan higienis<br><br>* Cocok untuk acara arisan, hadiah ataupun untuk dinikmati bersama keluarga dan teman kantor<br><br>* packing menggunakan kardus dan buble wrap (plastik dengan gelembung udara) sehingga tetap aman dalam proses pengiriman<br><br>* Komposisi : tepung terigu, gula, minyak nabati, air, kacang ijo, coklat<br><br><br><br>Produk terdaftar di kementrian kesehatan dan bersertifikat halal&nbsp;<br><br><br><br>Sertifikat halal : MUI No 03200017640817<br><br><br><br>Izin DepKes : DepKes RI P-IRT No 206360301006123<br><br><br><br>Kurir : SICEPAT , JNE, JNT, GOSEND DAN GRAB<br><br><br><br>Jadwal pengiriman gosend / grab<br><br>- Pesanan dikirim maksimal H+1 ( order hari ini maksimal dikirim besoknya)<br><br>- Hari minggu tidak ada pengiriman ( libur )<br><br>Jadi order sabtu dan minggu maksimal akan dikirim senin pagi<br><br>terima kasih ya.</p>',
            'img_main' => 'products/1/tAmgn0sGoDLBGhm1nQvpqO8aDlX3NSdNs3nDIgxt.webp',
            'img_top' => 'products/1/ZEA6TRiVNJcNfMEz42c0zZKyXvBApYjOBONw9icG.webp',
            'img_side' => 'products/1/q34SDqpSNCLkgbOGUoTo8Q1NlO4MIhAkEzqKWk20.webp',
            'img_front' => 'products/1/biG98kEmn8zvqOCRvsK9g8JPyNVf1fejsUqpCwkW.webp',
            'img_other' => NULL,
            'video' => NULL,
            'main_category' => 'Kue',
            'sub_category' => 'Kue Kering',
            'reg_code' => 'MUI No 03200017640817',
            'expired' => '2022-01-01',
            'durability' => 30,
            'preorder' => 1,
            'discount' => 1,
            'discount_price' => 31900.0,
            'hide' => 0,
            'created_at' => '2022-01-25 11:10:13',
            'updated_at' => '2022-01-25 11:10:13',
        ),
        6 => 
        array (
            'id' => 7,
            'user_id' => 1,
            'name' => 'Kue Mochi isi 12',
            'price' => 19420.0,
            'weight' => 300,
            'stock' => 2000,
            'description' => '<p>KUE MOCHI</p><p>Cemilan yang berasal dari negeri sakura Jepang. Dimodifikasi dengan isian kacang tanah dan cokelat. Praktis langsung santap.</p><p>Isi: 12 biji<br>Berat: 300gr</p><p>SARAN PENYAJIAN:<br>Langsung santap</p><p>SARAN PENYIMPANAN:<br>Kulkas / Freezer</p>',
            'img_main' => 'products/1/xHGj8xIw0MBWLvZbi0ARmRxLOrLLMgJKppXQY9Bz.webp',
            'img_top' => NULL,
            'img_side' => NULL,
            'img_front' => NULL,
            'img_other' => NULL,
            'video' => NULL,
            'main_category' => 'Cemilan / Snack',
            'sub_category' => 'Camilan Instant',
            'reg_code' => NULL,
            'expired' => '2022-01-01',
            'durability' => 90,
            'preorder' => 0,
            'discount' => 1,
            'discount_price' => 17500.0,
            'hide' => 0,
            'created_at' => '2022-01-25 11:13:39',
            'updated_at' => '2022-01-25 11:13:39',
        ),
        7 => 
        array (
            'id' => 8,
            'user_id' => 1,
            'name' => 'Kue MOCHI Rainbow isian kacang 16pcs',
            'price' => 35000.0,
            'weight' => 200,
            'stock' => 100,
            'description' => '<p><br>satu dus isi 16<br><br>isian kacang<br><br>Home made di buat sesuai pesanan, fresh from the oven<br><br><br><br>Kue mochi ini dibuat menggunakan bahan berkualitas dan TANPA BAHAN PENGAWET, jadi normal nya bisa bertahan hingga 3 sampai 4 hari.&nbsp;<br><br><br><br>Sebelum membeli, diskusikan dulu untuk ketersediaan barang yang akan dibeli, warna kue dan isian nya.&nbsp;<br><br><br><br>untuk pengiriman gosend sameday &amp; instant, pemesanan sebelum jam 4 sore ya, supaya bisa dikirim hari ini juga.</p>',
            'img_main' => 'products/1/64Xi6UO3ZtWS4xbgVIngNYHtfDXC4CQT2Gq9zWnz.webp',
            'img_top' => 'products/1/PPXcDFQ9YQH2xXpSyJbLgvQamn5NO33zGe2Y6cgA.webp',
            'img_side' => NULL,
            'img_front' => 'products/1/KYm2uwqRwFpnZMToEzGNccZzBMDUOBuxQGfxgeR5.webp',
            'img_other' => NULL,
            'video' => NULL,
            'main_category' => 'Kue',
            'sub_category' => 'Kue Basah',
            'reg_code' => NULL,
            'expired' => '2024-12-09',
            'durability' => NULL,
            'preorder' => 0,
            'discount' => 1,
            'discount_price' => 32000.0,
            'hide' => 0,
            'created_at' => '2022-01-25 11:17:50',
            'updated_at' => '2022-01-25 11:17:50',
        ),
        8 => 
        array (
            'id' => 9,
            'user_id' => 1,
            'name' => 'Batavia Cheese Stick Kue Kering Stik',
            'price' => 31000.0,
            'weight' => 200,
            'stock' => 50,
        'description' => '<p>Batavia Cheese Stick Kue Kering Stik Keju Snacks Renyah dan Bergizi</p><p>Produk yang kami tawarkan adalah camilan keju berkualitas yang sekarang sudah banyak dikenal dan dicari orang. Camilan produk kami ini tersebar di banyak Mall di Jakarta dan di beberapa lobby rumah sakit, khususnya RS. Siloam.</p><p>Rasa gurih kejunya dan kerenyahan adonannya yang pas Snack Cheese Stick ini sangat cocok dipadukan dengan menu utama lainnya seperti bubur ayam, nasi goreng, hingga steak.</p><p>Mengingat produk ini adalah makanan atau kue kering yang sangat renyah, maka untuk dapat cepat tiba di tujuan dan terhindar dari patah-patah (hancur) karena guncangan atau terbanting dalam pengiriman, makanya kami hanya menyarankan untuk menggunakan JASA PENGIRIMAN yang INSTANT, minimal yang SAMEDAY, baik dari Gosend atau Grab-Express.</p><p>Apabila menggunakan Jasa Pengiriman <strong>yang bukan Instant</strong> untuk produk ini, maka kami tidak bertanggung jawab atas kerusakan dalam pengiriman yang mungkin saja terjadi. Khusus bagi pelanggan dari luar kota, mohon pengertiannya agar dapat memaklumi kondisi tsb.</p><p>CATATAN:</p><ol><li>HARGA tercantum adalah harga untuk 1 botol toples.</li><li>Produk SELALU READY dan siap untuk di order.</li><li>Gunakanlah jasa pengiriman Gosend Instant atau Grab-Express INSTANT untuk hasil kondisi pengiriman terbaik.</li></ol>',
            'img_main' => 'products/1/9RYQf9kE69RqlA9dAfP6vxntUKRgThxTminbmkoI.webp',
            'img_top' => 'products/1/NGrMKtoVgaNZWDYEKXYC5wWapprxWPAk3kg8Vvtq.webp',
            'img_side' => 'products/1/jQ3L3YkKgZhyqU2ACQU19qWRdeTSNNKLU6yiG6Lm.webp',
            'img_front' => 'products/1/taNivwGa04ddyZaq59TcJzErzcYdTeQPLEugZT3a.webp',
            'img_other' => 'products/1/6nn9JYQ1noEQo7gYG5ZG6baAYLpr5N64HzBeCC3A.webp',
            'video' => NULL,
            'main_category' => 'Cemilan / Snack',
            'sub_category' => 'Keripik',
            'reg_code' => NULL,
            'expired' => '2024-02-13',
            'durability' => 180,
            'preorder' => 0,
            'discount' => 1,
            'discount_price' => 29900.0,
            'hide' => 0,
            'created_at' => '2022-01-25 11:22:05',
            'updated_at' => '2022-01-25 11:22:05',
        ),
        9 => 
        array (
            'id' => 10,
            'user_id' => 1,
            'name' => 'Kue Bawang Iris',
            'price' => 20000.0,
            'weight' => 250,
            'stock' => 100,
        'description' => '<p>Produk ini termasuk MAKANAN KERING<br>Daya Tahan (Kadaluarsa/Expired) 2 - 3 Bulan<br><br>Status Produk : READY (ALWAYS READYSTOCK)<br><br>Status Preorder, Jika :<br>1. Stok kosong<br>2. Limit Stok tidak mencukupi<br>3. Permintaan Customer untuk Produk baru<br>Lama Preorder 1 - 2 hari kerja<br><br>Berat yang tertera di atas (BERAT PRODUK) sudah termasuk kotak<br><br><br>Produk ini 100 % HALAL, tidak mengandung Perasa, Pewarna makanan, serta TANPA BAHAN PENGAWET<br><br>BEST SERVICE (Pelayanan Terbaik) bisa kami berikan kepada Customer :<br>1. Kami memastikan produk Pesanan anda selalu produk yang FRESH (Produksi Baru)<br>2. Kami memastikan pengiriman pesanan anda terkirim dengan cepat, dan sampai pesanan anda di tujuan dengan cepat pula.<br>3. Kami akan selalu follow up (update tracking) untuk pesanan anda, jika pesanan tersebut mengalami kendala di jasa pengiriman<br>4. kami selalu menerima kritik dan saran yang membangun untuk perkembangan toko online kami ini.<br><br>Ketika produk (pesanan) anda sampai, mohon memberikan REPUTASI (FEEDBACK) serta Review Produk karena itu dapat membantu kami lebih semangat dalam berTRANSAKSI JUALAN ONLINE</p>',
            'img_main' => 'products/1/ZVDGhMX8D89qTkSZZaiGKe4q0F91URwzvTs1bI51.webp',
            'img_top' => NULL,
            'img_side' => NULL,
            'img_front' => NULL,
            'img_other' => NULL,
            'video' => NULL,
            'main_category' => 'Cemilan / Snack',
            'sub_category' => 'Keripik',
            'reg_code' => NULL,
            'expired' => '2022-08-24',
            'durability' => 90,
            'preorder' => 0,
            'discount' => 1,
            'discount_price' => 19800.0,
            'hide' => 0,
            'created_at' => '2022-01-25 11:25:32',
            'updated_at' => '2022-01-25 11:25:32',
        ),
        10 => 
        array (
            'id' => 11,
            'user_id' => 1,
            'name' => 'KUE KERING manis GEM',
            'price' => 25000.0,
            'weight' => 500,
            'stock' => 50,
            'description' => '<p>Roti kering biscuit GEM SOLO 400gr gula warna warni manis renyah enak</p><p>roti kering tradisional kembang gula warna warni cocok untuk camilan bersama keluarga dan nostalgia... jaman kecil<br>enak renyah dan manis</p><p>berat 400gr<br>dimensi 25x15x7cm</p>',
            'img_main' => 'products/1/iDqqACGXBSZbU4X5owTHY8hQ1JFcm8wTOILe5nsc.webp',
            'img_top' => NULL,
            'img_side' => NULL,
            'img_front' => NULL,
            'img_other' => NULL,
            'video' => NULL,
            'main_category' => 'Kue',
            'sub_category' => 'Kue Kering',
            'reg_code' => NULL,
            'expired' => '2024-01-10',
            'durability' => 90,
            'preorder' => 0,
            'discount' => 1,
            'discount_price' => 17900.0,
            'hide' => 0,
            'created_at' => '2022-01-25 11:27:37',
            'updated_at' => '2022-01-25 11:28:45',
        ),
    ));
        
        
    }
}